### ISSUE TITLE
error on beautiful soup

### ISSUE THREAD

**Issue by himanshukansal** [rohithpr/py-web-search#6]
here's a screenshot:
![screenshot from 2015-01-30 20 09 19](https://cloud.githubusercontent.com/assets/8086282/5977254/0621de54-a8bc-11e4-87f3-0e08d59d2851.png)

**Comment by rohithpr** [comment]
From what I can tell, the problem is that you're using beautifulsoup meant for Python 2.
You don't need to have a copy of bs4 (that folder) once you you have installed it using pip.
You don't need to have a copy of pws either. Just do:

```
$ pip3 install beautifulsoup4
$ pip3 install requests
$ pip3 install py-web-search
```

Once you have done that, try executing the following in your home directory (or anywhere that isn't pws).

```
$ python3
>>> from pws.google import Google
```

**Comment by himanshukansal** [comment]
yes it worked fine no error..!But how to run script?

**Comment by rohithpr** [comment]
Please checkout the readme file.

``` python
from pws.google import Google
results = Google.search('hello world', num=20)
```

That will give you 20 results for 'hello world'.
